In [1]:
import numpy as np

In [2]:
#create a numpy array  with 20 integers
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
#create a 2 dementional numpy array from 0 to 20 w
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
#numpy arry of zeros (Floats)
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
#evenly spaced numbers 
np.linspace(0,50,21)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5, 30. , 32.5, 35. , 37.5, 40. , 42.5, 45. , 47.5, 50. ])

In [27]:
#random numbers  -> uniform distirnution from 0 and 1 -> same probility of being picked
np.random.rand(5,5)

array([[0.19806034, 0.15620206, 0.16567937, 0.03691785, 0.27753108],
       [0.67564167, 0.5936647 , 0.3046027 , 0.72647304, 0.6906856 ],
       [0.30792511, 0.51719859, 0.89603288, 0.52274071, 0.11877665],
       [0.26469237, 0.32154346, 0.3747192 , 0.39305437, 0.7753273 ],
       [0.17250783, 0.2035598 , 0.90756698, 0.83722226, 0.00975283]])

In [29]:
np.random.randn(4,5)

array([[ 1.65043496,  0.09006811, -0.71418037, -0.78073657,  0.45380737],
       [ 1.41369127,  0.21139568,  2.11017579,  1.1705231 ,  1.30086303],
       [-0.93367791, -0.69764233, -0.27340879, -0.81577045,  0.80405298],
       [-0.5848725 ,  1.40314786, -0.27206334, -1.9659827 ,  1.32807892]])