In [1]:
import numpy as np

In [3]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.random.rand(5,5)

array([[0.07234635, 0.82855757, 0.25528301, 0.45064055, 0.73131358],
       [0.13756198, 0.39383948, 0.60410378, 0.33137506, 0.60919746],
       [0.04373457, 0.34681255, 0.37791453, 0.97875796, 0.74094615],
       [0.95917604, 0.38113197, 0.22848974, 0.32269573, 0.71210239],
       [0.04932725, 0.32565548, 0.56674531, 0.58281374, 0.78676819]])

In [9]:
np.random.randn(5,5)

array([[-1.04188024,  0.29305673,  0.41380344, -0.72320402,  0.50085733],
       [-1.78697718,  1.35492892, -0.03941765, -0.34417032,  0.07390757],
       [-0.45498936,  0.29788068, -0.65693624, -0.6341675 ,  1.03385248],
       [-0.103806  ,  2.0903088 , -0.1720734 , -0.03776337,  0.07760056],
       [ 1.60427408,  1.22174268, -0.13200977,  1.64591106,  0.9466271 ]])

In [12]:
np.random.random(100)

array([0.18662797, 0.89708765, 0.52727399, 0.79339692, 0.26310029,
       0.71689071, 0.75863907, 0.60659718, 0.58665953, 0.54022204,
       0.77657441, 0.78055745, 0.8294256 , 0.42092981, 0.1833297 ,
       0.63013941, 0.51708495, 0.82490589, 0.18558677, 0.33071262,
       0.61005901, 0.84336074, 0.90223674, 0.45421534, 0.9578621 ,
       0.01089033, 0.31192263, 0.60934216, 0.59662687, 0.73161027,
       0.27469251, 0.1330449 , 0.93370409, 0.5668431 , 0.54557192,
       0.54357842, 0.20196021, 0.96870727, 0.67933049, 0.55079172,
       0.69373328, 0.98242092, 0.09460259, 0.47862551, 0.80570712,
       0.53347323, 0.4992012 , 0.5930431 , 0.03353007, 0.32637577,
       0.24127402, 0.95871449, 0.17676257, 0.8134645 , 0.39359406,
       0.91643771, 0.38339525, 0.22885059, 0.67898283, 0.18367205,
       0.97035621, 0.09225466, 0.06016537, 0.68755428, 0.59385314,
       0.99131476, 0.58505604, 0.07361626, 0.51822662, 0.17635183,
       0.54907041, 0.82944928, 0.20407149, 0.87627281, 0.17849

In [19]:
np.random.randint(0,100,10)

array([60, 90, 38, 62, 42,  0, 97, 69, 59, 46])

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr =  np.random.randint(0,50,10)

In [23]:
ranarr

array([13, 23, 48, 20,  4, 35,  7, 31,  1, 42])

In [24]:
# reshape -. takes the array and makes it a 2 dimantional array that adds up to the total amout of numbers
#inthe array 
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
#check the shape of the array 
arr.shape

(25,)

In [28]:
#check the datta type 
arr.dtype

dtype('int64')

In [30]:
#key methods 

ranarr.max()

48

In [35]:
#arg max checks the index of where the highest numbers sits
ranarr.argmax()
print(f"The hightest number in the arry is at index {ranarr.argmax()}")

The hightest number in the arry is at index 2


In [32]:
#chc kthe min 
ranarr.min()

1

In [36]:
#check the lowest index in the array 
ranarr.argmin()
print(f"The lowest number i nthe array is at the index {ranarr.argmin()}")

The lowest number i nthe array is at the index 8
