In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[0]

0

In [6]:
arr[0:3]

array([0, 1, 2])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#broadcasting -> Can change multiple items all at once -> this is a permenent change on the array sop be careful
arr[0:5] = 300

In [12]:
arr

array([300, 300, 300, 300, 300,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = arr[0:5]

In [18]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [19]:
slice_of_arr[:] = 99

In [22]:
# the original arry is still ehanged because o f memory issues -> only way is to create a new data set
#or ceate a copy of the current arry
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [23]:
#this is to prevent memory proiblems -. So  the original arry is edited and noy duplicated

indexing a 2 dementional array 

In [33]:
mat = np.array([[1,2,3,4],[5,6,7,8,],[10,11,12,13]])

In [34]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [35]:
#index an intire row 
mat[0]

array([1, 2, 3, 4])

In [36]:
mat[1]

array([5, 6, 7, 8])

In [37]:
mat[2]

array([10, 11, 12, 13])

In [38]:
mat[0,1]

2

In [39]:
#index our  4 on the first row 
mat[0,3]

4

In [40]:
#slice the matrix -> get a matrix from the first two rows and last 3 columns
mat[0:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [41]:
#conditional  Selection 
arr = np.arange(1,11)

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
bool_arr = arr > 4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])