In [1]:
import numpy as np

In [2]:
#vector and matrix (can still have one row and columns)

In [3]:
#creting an array
my_list  = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [4]:
#creating a 2 dimentional; array
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
np.array(my_matrix)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
#create . range with nu,py veraion of range
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# create a zero matrix eith 3 floats
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
#2d matrix using zeros 
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
#lets work with ones 
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# you can retun even spaced numbers over an interval
#lin sppace - > start stop and how many numbers in between you want
#So givem e alist of 20 numbers between 0 and 21 (21 due to index 0)
#every number in here has the same probility of being picked 
np.linspace(0,20,21)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [16]:
#numpy rand -> give you a list of numbers between 0 and 1
np.random.rand(2)

array([0.4857082 , 0.95018168])

In [18]:
#you cna alo use this to decide on a matrix containing numbers that are between 0 and 1 
np.random.rand(5,5)

array([[0.20814391, 0.38249593, 0.80210472, 0.30720503, 0.19775253],
       [0.64892677, 0.11942099, 0.87367427, 0.53587407, 0.43804762],
       [0.47864052, 0.24738551, 0.84528008, 0.19095496, 0.20714751],
       [0.51515411, 0.72445916, 0.15137995, 0.71813927, 0.63403803],
       [0.37266233, 0.83301059, 0.98500428, 0.21312861, 0.14441346]])

In [20]:
#numpy randn -> mean centered around 1 -> Normal Distribution -> mean is 0 and variance of 1 -> can have some negative
np.random.randn(5,4)

array([[ 0.76473389,  0.86540947,  1.08224682,  1.63858979],
       [-1.03220185, -1.5813344 ,  1.20469801,  0.83983559],
       [-0.20214006, -1.20987905, -1.82555073, -1.23677723],
       [ 2.08437006, -1.00566023,  0.1654323 ,  0.16869079],
       [ 0.45005231, -0.46825471,  1.9609975 ,  1.32358243]])

In [30]:
#np . random integer 
arr = np.random.randint(1,100, 10)
arr

array([32, 71, 24, 69, 59, 21, 50, 43, 52, 97])

In [29]:
arr.argmax()

8