In [1]:
#create a numpy array using the rand, arange, random, randnm ethods
#reshape an array to have s 4,2 demension 
#create a data frame using numpy arrays create from the random method,m dictionaries, and a api call

#what is unique and nUnique and how are they used 
#wgat is value_counts and how does it work
#use group by and explain what it does
#user sort _values and explain what it does
#use the apply methos on a data frame using a function and a lambda expression 
#remove a column from athe data frame and remove a row as well
#append the coliumn back to the data set with new data
#ger the columns names for the data frame and . also the index 
#Finde the null values in data frame
#use group by and explain what it does -> use some aggregate function on the data frame
#use describe function on the df return on the group by method -> Columns (Transpose)vs rows

In [25]:
import numpy as np
import pandas as pd

In [8]:
arry = np.random.rand(3,2)

In [9]:
arry

array([[0.68978616, 0.41701533],
       [0.53659832, 0.72506397],
       [0.25569783, 0.97466018]])

In [12]:
ar = np.random.randn(3,3)

In [13]:
ar

array([[-0.02002856, -0.48088428,  1.18600965],
       [ 1.01102609,  1.6758589 ,  0.15414495],
       [ 2.07764852, -1.08078076, -0.26513194]])

In [18]:
aar = np.random.randint(0,50,20)

In [19]:
aar

array([37,  6, 17, 19,  3, 20, 22, 18, 34, 21, 23, 49,  7, 21,  1, 45, 18,
        0, 49, 15])

In [20]:
lii = [3,4,5,6,7,8,8,6]

In [24]:
arar  = np.array(lii)
arar.reshape(4,2)

array([[3, 4],
       [5, 6],
       [7, 8],
       [8, 6]])

In [39]:
data = np.random.rand(5,5)
df = pd.DataFrame(data, index = ["Berkat", "Jerry", "Femi", "Roe", "Jill"], columns= ["sss", "gg", "gggg","dfdf", "dfdf"])

In [40]:
df

sss        gg      gggg      dfdf      dfdf
Berkat  0.815020  0.241775  0.328302  0.565392  0.846920
Jerry   0.343573  0.419254  0.857582  0.938891  0.320602
Femi    0.885156  0.006423  0.313279  0.229624  0.902523
Roe     0.345886  0.372439  0.198305  0.877835  0.785559
Jill    0.257079  0.977209  0.028385  0.181726  0.093941

In [43]:
dat = {"English":[87,67,55,89,91], "Math": [77,88,87,99,76]}
dff = pd.DataFrame(dat, index = ["Berkat", "Jerry", "Femi", "Roe", "Jill"] )

In [44]:
dff

English  Math
Berkat       87    77
Jerry        67    88
Femi         55    87
Roe          89    99
Jill         91    76

In [45]:
dff["Math"]

Berkat    77
Jerry     88
Femi      87
Roe       99
Jill      76
Name: Math, dtype: int64

In [46]:
dff[dff["Math"] > 80]

English  Math
Jerry       67    88
Femi        55    87
Roe         89    99